apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuers.production.name }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuers.production.email }}
    privateKeySecretRef:
      name: {{ .Values.issuers.production.name }}
    solvers:
      {{ if .Values.solvers.http01.enabled }}
      - http01:
          ingress: {{ .Values.solvers.http01.ingress }}
      {{ end }}
