apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuers.staging.name }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuers.staging.email }}
    privateKeySecretRef:
      name: {{ .Values.issuers.staging.name }}
    solvers:
      - http01:
          ingress: {}
