apiVersion: v2
name: acme-cluster-issuer
description: |
  Deploys a production/staging pair of ACME cert-manager cluster issuer into a Kubernetes cluster. Cert-Manager must 
  already be installed and running prior to this chart being installed.
type: application
version: 0.2.1
appVersion: "1.10.1"
